### PR TITLE
Update tflite to v2.9.1 and support kirkstone (the latest yocto release)

### PR DESCRIPTION
**Pull request by anyj0527**
- Add recipe for TensorFlow Lite v2.9.1 release
- Support kirkstone

### CODE REVIEW

**Comment by myungjoo** [comment]
Build tested?

**Comment by anyj0527** [comment]
> Build tested?

Yes, but the new yocto release kirkstone requires backward breaking changes in recipes. I think we better add a branch sth like `dunfell` to support dunfell - versions. How about this?

**Comment by myungjoo** [comment]
> > Build tested?
> 
> Yes, but the new yocto release kirkstone requires backward breaking changes in recipes. I think we better add a branch sth like `dunfell` to support dunfell - versions. How about this?

Can you do something like ```if dunfell then X elif kirkstone Y``` in .bb script?

**Comment by anyj0527** [comment]
> > > Build tested?
> > 
> > 
> > Yes, but the new yocto release kirkstone requires backward breaking changes in recipes. I think we better add a branch sth like `dunfell` to support dunfell - versions. How about this?
> 
> Can you do something like `if dunfell then X elif kirkstone Y` in .bb script?

It could be possible but does not seems proper. Many meta-* maintain each release branches along with master (main) branch.

**Comment by myungjoo** [comment]
> > > > Build tested?
> > > 
> > > 
> > > Yes, but the new yocto release kirkstone requires backward breaking changes in recipes. I think we better add a branch sth like `dunfell` to support dunfell - versions. How about this?
> > 
> > 
> > Can you do something like `if dunfell then X elif kirkstone Y` in .bb script?
> 
> It could be possible but does not seems proper. Many meta-* maintain each release branches along with master (main) branch.

Ok.. you may branch out dunfell with the condition that there will be NO MORE changes (except for hot fixes) in the dunfell branch.

**Comment by anyj0527** [comment]
https://layers.openembedded.org/layerindex/branch/dunfell/layer/meta-neural-network/
I branched out the dunfell branch. And the OpenEmbedded automatically fetched the branch.

**Review by myungjoo — APPROVED** [review]
LGTM!

**Pull request merged**
