### PR TITLE
Update nntrainer: 0.1.1 --> 0.2.0

### LINKED ISSUE #67: NNtrainer yocto-build.patch file "0001-Patch-for-yocto-build.patch" not upgraded with latest meson.build file in nntrainer repo
Hi,

We tried to build the meta-neural-network layer for nnstreamer. While building, we observed that the patch files for yocto build are not up-to-date with the latest meson.build files (example yocto build file for nntrainer).

Because of this, we receive errors during the build. PFA for the txt file indicating the errors.

Can you please provide the updated files, so that the patch can be directly applied to the build ? 
[build_failed.txt](https://github.com/nnstreamer/meta-neural-network/files/6877366/build_failed.txt)

### PR DESCRIPTION
**Pull request by myungjoo**
Update nntrainer yocto support for 0.2.0
Fixes #67
CC: @ptrivedi2610  

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

**Comment by anyj0527** [comment]
Since the nntrainer recipe is not tested for quite long time, just removing patch file won't make it to be built...
Please consider #75.

**Comment by ptrivedi2610** [comment]
@anyj0527  @myungjoo 

Yes, we are unable to build with the new update.
PFA for the log file containing build errors
[error-log-for-new-release-nntrainer.txt](https://github.com/nnstreamer/meta-neural-network/files/6973590/error-log-for-new-release-nntrainer.txt)

**Comment by ptrivedi2610** [comment]
@anyj0527 

Thanks for the quick response.
But now we get the below error. PFA for the log file
[error-log-for-nnstreamer_do_package_failed.txt](https://github.com/nnstreamer/meta-neural-network/files/6975547/error-log-for-nnstreamer_do_package_failed.txt)

**Comment by anyj0527** [comment]
Please check this line: https://github.com/nnstreamer/meta-neural-network/blob/master/recipes-nnstreamer/nnstreamer/nnstreamer_1.7.2.bb#L46
It removes those files during the install phase. You may check whether your recipe is up to date.

**Pull request closed without merging**
