### PR TITLE
Add recipe for TensorFlow Lite v2.6.0 @open sesame 11/11 10:36

### PR DESCRIPTION
**Pull request by anyj0527**
- Add the recipe for tflite-v2.6.0
- Add a patch to fix cmake build script and a pc file
- This recipe generates static library name "libtensorflow2-lite.a" and
  header files of tflite and flatbuffers

- Exclude zeus from the compat poky distro
  (TFLite v2.6.0 requires cmake version after dunfell)
- Let nnstreamer package "...tensorflow2-lite.so"

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Comment by myungjoo** [comment]
> * Exclude zeus from the compat poky distro
>   (TFLite v2.6.0 requires cmake version after dunfell)

Can you exclude zeus only for tflite 2.6.0 build?

**Comment by wooksong** [comment]
https://wiki.yoctoproject.org/wiki/Releases

IMO, we can drop the support for Zeus.

**Review by myungjoo — APPROVED** [review]
LGTM. Let's drop zeus.

Anyway, please take a look at the CI error.

**Comment by anyj0527** [comment]
@myungjoo Updated the CI's local poky distro to dunfell. PTAL

**Pull request merged**
